I = imread('./images/lenna.png');
J = threshold(I,80);
h1 = histogram(rgb2gray(I));
h2 = histogram(J);
subplot(2,2,1);
imshow(rgb2gray(I));
hold on;
subplot(2,2,2);
plot(h1);
subplot(2,2,3);
imshow(J);
hold on;
subplot(2,2,4);
plot(h2);